// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: paraspeech/v1/common.proto

package paraspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeName      string                 `protobuf:"bytes,2,opt,name=code_name,json=codeName,proto3" json:"code_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_paraspeech_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_paraspeech_v1_common_proto protoreflect.FileDescriptor

const file_paraspeech_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aparaspeech/v1/common.proto\x12\rparaspeech.v1\"\xd7\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1b\n" +
	"\tcode_name\x18\x02 \x01(\tR\bcodeName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12A\n" +
	"\adetails\x18\x04 \x03(\v2'.paraspeech.v1.ErrorDetail.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B1Z/paraspeech/api/proto/paraspeech/v1;paraspeechv1b\x06proto3"

var (
	file_paraspeech_v1_common_proto_rawDescOnce sync.Once
	file_paraspeech_v1_common_proto_rawDescData []byte
)

func file_paraspeech_v1_common_proto_rawDescGZIP() []byte {
	file_paraspeech_v1_common_proto_rawDescOnce.Do(func() {
		file_paraspeech_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paraspeech_v1_common_proto_rawDesc), len(file_paraspeech_v1_common_proto_rawDesc)))
	})
	return file_paraspeech_v1_common_proto_rawDescData
}

var file_paraspeech_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paraspeech_v1_common_proto_goTypes = []any{
	(*ErrorDetail)(nil), // 0: paraspeech.v1.ErrorDetail
	nil,                 // 1: paraspeech.v1.ErrorDetail.DetailsEntry
}
var file_paraspeech_v1_common_proto_depIdxs = []int32{
	1, // 0: paraspeech.v1.ErrorDetail.details:type_name -> paraspeech.v1.ErrorDetail.DetailsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paraspeech_v1_common_proto_init() }
func file_paraspeech_v1_common_proto_init() {
	if File_paraspeech_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paraspeech_v1_common_proto_rawDesc), len(file_paraspeech_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paraspeech_v1_common_proto_goTypes,
		DependencyIndexes: file_paraspeech_v1_common_proto_depIdxs,
		MessageInfos:      file_paraspeech_v1_common_proto_msgTypes,
	}.Build()
	File_paraspeech_v1_common_proto = out.File
	file_paraspeech_v1_common_proto_goTypes = nil
	file_paraspeech_v1_common_proto_depIdxs = nil
}
