// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: paraspeech/v1/health.proto

package paraspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_paraspeech_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_health_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Stt           *ChannelHealth         `protobuf:"bytes,4,opt,name=stt,proto3" json:"stt,omitempty"`
	Tts           *ChannelHealth         `protobuf:"bytes,5,opt,name=tts,proto3" json:"tts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_paraspeech_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetStt() *ChannelHealth {
	if x != nil {
		return x.Stt
	}
	return nil
}

func (x *HealthResponse) GetTts() *ChannelHealth {
	if x != nil {
		return x.Tts
	}
	return nil
}

type ChannelHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	VadMode       string                 `protobuf:"bytes,3,opt,name=vad_mode,json=vadMode,proto3" json:"vad_mode,omitempty"`
	VaultReady    bool                   `protobuf:"varint,4,opt,name=vault_ready,json=vaultReady,proto3" json:"vault_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelHealth) Reset() {
	*x = ChannelHealth{}
	mi := &file_paraspeech_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelHealth) ProtoMessage() {}

func (x *ChannelHealth) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelHealth.ProtoReflect.Descriptor instead.
func (*ChannelHealth) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelHealth) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChannelHealth) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChannelHealth) GetVadMode() string {
	if x != nil {
		return x.VadMode
	}
	return ""
}

func (x *ChannelHealth) GetVaultReady() bool {
	if x != nil {
		return x.VaultReady
	}
	return false
}

var File_paraspeech_v1_health_proto protoreflect.FileDescriptor

const file_paraspeech_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1aparaspeech/v1/health.proto\x12\rparaspeech.v1\"\x0f\n" +
	"\rHealthRequest\"\xb4\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12.\n" +
	"\x03stt\x18\x04 \x01(\v2\x1c.paraspeech.v1.ChannelHealthR\x03stt\x12.\n" +
	"\x03tts\x18\x05 \x01(\v2\x1c.paraspeech.v1.ChannelHealthR\x03tts\"{\n" +
	"\rChannelHealth\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x19\n" +
	"\bvad_mode\x18\x03 \x01(\tR\avadMode\x12\x1f\n" +
	"\vvault_ready\x18\x04 \x01(\bR\n" +
	"vaultReady2U\n" +
	"\rHealthService\x12D\n" +
	"\x05Check\x12\x1c.paraspeech.v1.HealthRequest\x1a\x1d.paraspeech.v1.HealthResponseB1Z/paraspeech/api/proto/paraspeech/v1;paraspeechv1b\x06proto3"

var (
	file_paraspeech_v1_health_proto_rawDescOnce sync.Once
	file_paraspeech_v1_health_proto_rawDescData []byte
)

func file_paraspeech_v1_health_proto_rawDescGZIP() []byte {
	file_paraspeech_v1_health_proto_rawDescOnce.Do(func() {
		file_paraspeech_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paraspeech_v1_health_proto_rawDesc), len(file_paraspeech_v1_health_proto_rawDesc)))
	})
	return file_paraspeech_v1_health_proto_rawDescData
}

var file_paraspeech_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_paraspeech_v1_health_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: paraspeech.v1.HealthRequest
	(*HealthResponse)(nil), // 1: paraspeech.v1.HealthResponse
	(*ChannelHealth)(nil),  // 2: paraspeech.v1.ChannelHealth
}
var file_paraspeech_v1_health_proto_depIdxs = []int32{
	2, // 0: paraspeech.v1.HealthResponse.stt:type_name -> paraspeech.v1.ChannelHealth
	2, // 1: paraspeech.v1.HealthResponse.tts:type_name -> paraspeech.v1.ChannelHealth
	0, // 2: paraspeech.v1.HealthService.Check:input_type -> paraspeech.v1.HealthRequest
	1, // 3: paraspeech.v1.HealthService.Check:output_type -> paraspeech.v1.HealthResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_paraspeech_v1_health_proto_init() }
func file_paraspeech_v1_health_proto_init() {
	if File_paraspeech_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paraspeech_v1_health_proto_rawDesc), len(file_paraspeech_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paraspeech_v1_health_proto_goTypes,
		DependencyIndexes: file_paraspeech_v1_health_proto_depIdxs,
		MessageInfos:      file_paraspeech_v1_health_proto_msgTypes,
	}.Build()
	File_paraspeech_v1_health_proto = out.File
	file_paraspeech_v1_health_proto_goTypes = nil
	file_paraspeech_v1_health_proto_depIdxs = nil
}
