// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: paraspeech/v1/stt.proto

package paraspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	VadDebug      bool                   `protobuf:"varint,5,opt,name=vad_debug,json=vadDebug,proto3" json:"vad_debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *TranscribeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TranscribeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscribeRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TranscribeRequest) GetVadDebug() bool {
	if x != nil {
		return x.VadDebug
	}
	return false
}

type TranscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Meta          *TranscribeMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetMeta() *TranscribeMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TranscribeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	AudioMs       int64                  `protobuf:"varint,2,opt,name=audio_ms,json=audioMs,proto3" json:"audio_ms,omitempty"`
	ProcessMs     int64                  `protobuf:"varint,3,opt,name=process_ms,json=processMs,proto3" json:"process_ms,omitempty"`
	Vad           *VadMeta               `protobuf:"bytes,4,opt,name=vad,proto3" json:"vad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeMeta) Reset() {
	*x = TranscribeMeta{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeMeta) ProtoMessage() {}

func (x *TranscribeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeMeta.ProtoReflect.Descriptor instead.
func (*TranscribeMeta) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeMeta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TranscribeMeta) GetAudioMs() int64 {
	if x != nil {
		return x.AudioMs
	}
	return 0
}

func (x *TranscribeMeta) GetProcessMs() int64 {
	if x != nil {
		return x.ProcessMs
	}
	return 0
}

func (x *TranscribeMeta) GetVad() *VadMeta {
	if x != nil {
		return x.Vad
	}
	return nil
}

type VadMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Fallback      bool                   `protobuf:"varint,3,opt,name=fallback,proto3" json:"fallback,omitempty"`
	AudioMsBefore int64                  `protobuf:"varint,4,opt,name=audio_ms_before,json=audioMsBefore,proto3" json:"audio_ms_before,omitempty"`
	AudioMsAfter  int64                  `protobuf:"varint,5,opt,name=audio_ms_after,json=audioMsAfter,proto3" json:"audio_ms_after,omitempty"`
	TrimRatio     float64                `protobuf:"fixed64,6,opt,name=trim_ratio,json=trimRatio,proto3" json:"trim_ratio,omitempty"`
	SegmentsCount int32                  `protobuf:"varint,7,opt,name=segments_count,json=segmentsCount,proto3" json:"segments_count,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,8,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VadMeta) Reset() {
	*x = VadMeta{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VadMeta) ProtoMessage() {}

func (x *VadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VadMeta.ProtoReflect.Descriptor instead.
func (*VadMeta) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{3}
}

func (x *VadMeta) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *VadMeta) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VadMeta) GetFallback() bool {
	if x != nil {
		return x.Fallback
	}
	return false
}

func (x *VadMeta) GetAudioMsBefore() int64 {
	if x != nil {
		return x.AudioMsBefore
	}
	return 0
}

func (x *VadMeta) GetAudioMsAfter() int64 {
	if x != nil {
		return x.AudioMsAfter
	}
	return 0
}

func (x *VadMeta) GetTrimRatio() float64 {
	if x != nil {
		return x.TrimRatio
	}
	return 0
}

func (x *VadMeta) GetSegmentsCount() int32 {
	if x != nil {
		return x.SegmentsCount
	}
	return 0
}

func (x *VadMeta) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type AudioFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	EndOfAudio    bool                   `protobuf:"varint,2,opt,name=end_of_audio,json=endOfAudio,proto3" json:"end_of_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{4}
}

func (x *AudioFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioFrame) GetEndOfAudio() bool {
	if x != nil {
		return x.EndOfAudio
	}
	return false
}

type TranscribeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*TranscribeEvent_Partial
	//	*TranscribeEvent_Final
	//	*TranscribeEvent_Error
	Event         isTranscribeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeEvent) Reset() {
	*x = TranscribeEvent{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeEvent) ProtoMessage() {}

func (x *TranscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeEvent.ProtoReflect.Descriptor instead.
func (*TranscribeEvent) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{5}
}

func (x *TranscribeEvent) GetEvent() isTranscribeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TranscribeEvent) GetPartial() *PartialResult {
	if x != nil {
		if x, ok := x.Event.(*TranscribeEvent_Partial); ok {
			return x.Partial
		}
	}
	return nil
}

func (x *TranscribeEvent) GetFinal() *FinalResult {
	if x != nil {
		if x, ok := x.Event.(*TranscribeEvent_Final); ok {
			return x.Final
		}
	}
	return nil
}

func (x *TranscribeEvent) GetError() *TranscribeError {
	if x != nil {
		if x, ok := x.Event.(*TranscribeEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTranscribeEvent_Event interface {
	isTranscribeEvent_Event()
}

type TranscribeEvent_Partial struct {
	Partial *PartialResult `protobuf:"bytes,1,opt,name=partial,proto3,oneof"`
}

type TranscribeEvent_Final struct {
	Final *FinalResult `protobuf:"bytes,2,opt,name=final,proto3,oneof"`
}

type TranscribeEvent_Error struct {
	Error *TranscribeError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*TranscribeEvent_Partial) isTranscribeEvent_Event() {}

func (*TranscribeEvent_Final) isTranscribeEvent_Event() {}

func (*TranscribeEvent_Error) isTranscribeEvent_Event() {}

type PartialResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Index           int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	StartSec        float64                `protobuf:"fixed64,2,opt,name=start_sec,json=startSec,proto3" json:"start_sec,omitempty"`
	EndSec          float64                `protobuf:"fixed64,3,opt,name=end_sec,json=endSec,proto3" json:"end_sec,omitempty"`
	Text            string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	AccumulatedText string                 `protobuf:"bytes,5,opt,name=accumulated_text,json=accumulatedText,proto3" json:"accumulated_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartialResult) Reset() {
	*x = PartialResult{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialResult) ProtoMessage() {}

func (x *PartialResult) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialResult.ProtoReflect.Descriptor instead.
func (*PartialResult) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{6}
}

func (x *PartialResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PartialResult) GetStartSec() float64 {
	if x != nil {
		return x.StartSec
	}
	return 0
}

func (x *PartialResult) GetEndSec() float64 {
	if x != nil {
		return x.EndSec
	}
	return 0
}

func (x *PartialResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PartialResult) GetAccumulatedText() string {
	if x != nil {
		return x.AccumulatedText
	}
	return ""
}

type FinalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Chunks        int32                  `protobuf:"varint,2,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Meta          *TranscribeMeta        `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalResult) Reset() {
	*x = FinalResult{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalResult) ProtoMessage() {}

func (x *FinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalResult.ProtoReflect.Descriptor instead.
func (*FinalResult) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{7}
}

func (x *FinalResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FinalResult) GetChunks() int32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *FinalResult) GetMeta() *TranscribeMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TranscribeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeError) Reset() {
	*x = TranscribeError{}
	mi := &file_paraspeech_v1_stt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeError) ProtoMessage() {}

func (x *TranscribeError) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_stt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeError.ProtoReflect.Descriptor instead.
func (*TranscribeError) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_stt_proto_rawDescGZIP(), []int{8}
}

func (x *TranscribeError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TranscribeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_paraspeech_v1_stt_proto protoreflect.FileDescriptor

const file_paraspeech_v1_stt_proto_rawDesc = "" +
	"\n" +
	"\x17paraspeech/v1/stt.proto\x12\rparaspeech.v1\"\x94\x01\n" +
	"\x11TranscribeRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1b\n" +
	"\tvad_debug\x18\x05 \x01(\bR\bvadDebug\"[\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x121\n" +
	"\x04meta\x18\x02 \x01(\v2\x1d.paraspeech.v1.TranscribeMetaR\x04meta\"\x8f\x01\n" +
	"\x0eTranscribeMeta\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\baudio_ms\x18\x02 \x01(\x03R\aaudioMs\x12\x1d\n" +
	"\n" +
	"process_ms\x18\x03 \x01(\x03R\tprocessMs\x12(\n" +
	"\x03vad\x18\x04 \x01(\v2\x16.paraspeech.v1.VadMetaR\x03vad\"\x8a\x02\n" +
	"\aVadMeta\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1a\n" +
	"\bfallback\x18\x03 \x01(\bR\bfallback\x12&\n" +
	"\x0faudio_ms_before\x18\x04 \x01(\x03R\raudioMsBefore\x12$\n" +
	"\x0eaudio_ms_after\x18\x05 \x01(\x03R\faudioMsAfter\x12\x1d\n" +
	"\n" +
	"trim_ratio\x18\x06 \x01(\x01R\ttrimRatio\x12%\n" +
	"\x0esegments_count\x18\a \x01(\x05R\rsegmentsCount\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\b \x01(\x03R\telapsedMs\"B\n" +
	"\n" +
	"AudioFrame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12 \n" +
	"\fend_of_audio\x18\x02 \x01(\bR\n" +
	"endOfAudio\"\xc0\x01\n" +
	"\x0fTranscribeEvent\x128\n" +
	"\apartial\x18\x01 \x01(\v2\x1c.paraspeech.v1.PartialResultH\x00R\apartial\x122\n" +
	"\x05final\x18\x02 \x01(\v2\x1a.paraspeech.v1.FinalResultH\x00R\x05final\x126\n" +
	"\x05error\x18\x03 \x01(\v2\x1e.paraspeech.v1.TranscribeErrorH\x00R\x05errorB\a\n" +
	"\x05event\"\x9a\x01\n" +
	"\rPartialResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1b\n" +
	"\tstart_sec\x18\x02 \x01(\x01R\bstartSec\x12\x17\n" +
	"\aend_sec\x18\x03 \x01(\x01R\x06endSec\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12)\n" +
	"\x10accumulated_text\x18\x05 \x01(\tR\x0faccumulatedText\"l\n" +
	"\vFinalResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06chunks\x18\x02 \x01(\x05R\x06chunks\x121\n" +
	"\x04meta\x18\x03 \x01(\v2\x1d.paraspeech.v1.TranscribeMetaR\x04meta\"?\n" +
	"\x0fTranscribeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb2\x01\n" +
	"\n" +
	"STTService\x12Q\n" +
	"\n" +
	"Transcribe\x12 .paraspeech.v1.TranscribeRequest\x1a!.paraspeech.v1.TranscribeResponse\x12Q\n" +
	"\x10TranscribeStream\x12\x19.paraspeech.v1.AudioFrame\x1a\x1e.paraspeech.v1.TranscribeEvent(\x010\x01B1Z/paraspeech/api/proto/paraspeech/v1;paraspeechv1b\x06proto3"

var (
	file_paraspeech_v1_stt_proto_rawDescOnce sync.Once
	file_paraspeech_v1_stt_proto_rawDescData []byte
)

func file_paraspeech_v1_stt_proto_rawDescGZIP() []byte {
	file_paraspeech_v1_stt_proto_rawDescOnce.Do(func() {
		file_paraspeech_v1_stt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paraspeech_v1_stt_proto_rawDesc), len(file_paraspeech_v1_stt_proto_rawDesc)))
	})
	return file_paraspeech_v1_stt_proto_rawDescData
}

var file_paraspeech_v1_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_paraspeech_v1_stt_proto_goTypes = []any{
	(*TranscribeRequest)(nil),  // 0: paraspeech.v1.TranscribeRequest
	(*TranscribeResponse)(nil), // 1: paraspeech.v1.TranscribeResponse
	(*TranscribeMeta)(nil),     // 2: paraspeech.v1.TranscribeMeta
	(*VadMeta)(nil),            // 3: paraspeech.v1.VadMeta
	(*AudioFrame)(nil),         // 4: paraspeech.v1.AudioFrame
	(*TranscribeEvent)(nil),    // 5: paraspeech.v1.TranscribeEvent
	(*PartialResult)(nil),      // 6: paraspeech.v1.PartialResult
	(*FinalResult)(nil),        // 7: paraspeech.v1.FinalResult
	(*TranscribeError)(nil),    // 8: paraspeech.v1.TranscribeError
}
var file_paraspeech_v1_stt_proto_depIdxs = []int32{
	2, // 0: paraspeech.v1.TranscribeResponse.meta:type_name -> paraspeech.v1.TranscribeMeta
	3, // 1: paraspeech.v1.TranscribeMeta.vad:type_name -> paraspeech.v1.VadMeta
	6, // 2: paraspeech.v1.TranscribeEvent.partial:type_name -> paraspeech.v1.PartialResult
	7, // 3: paraspeech.v1.TranscribeEvent.final:type_name -> paraspeech.v1.FinalResult
	8, // 4: paraspeech.v1.TranscribeEvent.error:type_name -> paraspeech.v1.TranscribeError
	2, // 5: paraspeech.v1.FinalResult.meta:type_name -> paraspeech.v1.TranscribeMeta
	0, // 6: paraspeech.v1.STTService.Transcribe:input_type -> paraspeech.v1.TranscribeRequest
	4, // 7: paraspeech.v1.STTService.TranscribeStream:input_type -> paraspeech.v1.AudioFrame
	1, // 8: paraspeech.v1.STTService.Transcribe:output_type -> paraspeech.v1.TranscribeResponse
	5, // 9: paraspeech.v1.STTService.TranscribeStream:output_type -> paraspeech.v1.TranscribeEvent
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_paraspeech_v1_stt_proto_init() }
func file_paraspeech_v1_stt_proto_init() {
	if File_paraspeech_v1_stt_proto != nil {
		return
	}
	file_paraspeech_v1_stt_proto_msgTypes[5].OneofWrappers = []any{
		(*TranscribeEvent_Partial)(nil),
		(*TranscribeEvent_Final)(nil),
		(*TranscribeEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paraspeech_v1_stt_proto_rawDesc), len(file_paraspeech_v1_stt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paraspeech_v1_stt_proto_goTypes,
		DependencyIndexes: file_paraspeech_v1_stt_proto_depIdxs,
		MessageInfos:      file_paraspeech_v1_stt_proto_msgTypes,
	}.Build()
	File_paraspeech_v1_stt_proto = out.File
	file_paraspeech_v1_stt_proto_goTypes = nil
	file_paraspeech_v1_stt_proto_depIdxs = nil
}
