// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: paraspeech/v1/tts.proto

package paraspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	VoiceProfile  *VoiceProfile          `protobuf:"bytes,3,opt,name=voice_profile,json=voiceProfile,proto3" json:"voice_profile,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	MaxSec        float64                `protobuf:"fixed64,6,opt,name=max_sec,json=maxSec,proto3" json:"max_sec,omitempty"`
	OutDir        string                 `protobuf:"bytes,7,opt,name=out_dir,json=outDir,proto3" json:"out_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{0}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *SynthesizeRequest) GetVoiceProfile() *VoiceProfile {
	if x != nil {
		return x.VoiceProfile
	}
	return nil
}

func (x *SynthesizeRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SynthesizeRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SynthesizeRequest) GetMaxSec() float64 {
	if x != nil {
		return x.MaxSec
	}
	return 0
}

func (x *SynthesizeRequest) GetOutDir() string {
	if x != nil {
		return x.OutDir
	}
	return ""
}

type VoiceProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voice         string                 `protobuf:"bytes,1,opt,name=voice,proto3" json:"voice,omitempty"`
	Speed         float64                `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`
	Emotion       string                 `protobuf:"bytes,3,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Pitch         string                 `protobuf:"bytes,4,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Style         string                 `protobuf:"bytes,5,opt,name=style,proto3" json:"style,omitempty"`
	Custom        map[string]string      `protobuf:"bytes,6,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceProfile) Reset() {
	*x = VoiceProfile{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceProfile) ProtoMessage() {}

func (x *VoiceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceProfile.ProtoReflect.Descriptor instead.
func (*VoiceProfile) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceProfile) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *VoiceProfile) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *VoiceProfile) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *VoiceProfile) GetPitch() string {
	if x != nil {
		return x.Pitch
	}
	return ""
}

func (x *VoiceProfile) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *VoiceProfile) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

type SynthesizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Segments      []*SynthesizeSegment   `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	Meta          *SynthesizeMeta        `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{2}
}

func (x *SynthesizeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SynthesizeResponse) GetSegments() []*SynthesizeSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *SynthesizeResponse) GetMeta() *SynthesizeMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type SynthesizeSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	EstimatedSec  float64                `protobuf:"fixed64,3,opt,name=estimated_sec,json=estimatedSec,proto3" json:"estimated_sec,omitempty"`
	Audio         []byte                 `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeSegment) Reset() {
	*x = SynthesizeSegment{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSegment) ProtoMessage() {}

func (x *SynthesizeSegment) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSegment.ProtoReflect.Descriptor instead.
func (*SynthesizeSegment) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{3}
}

func (x *SynthesizeSegment) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SynthesizeSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeSegment) GetEstimatedSec() float64 {
	if x != nil {
		return x.EstimatedSec
	}
	return 0
}

func (x *SynthesizeSegment) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *SynthesizeSegment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SynthesizeSegment) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SynthesizeSegment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type SynthesizeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	VoiceProfile  *VoiceProfile          `protobuf:"bytes,2,opt,name=voice_profile,json=voiceProfile,proto3" json:"voice_profile,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	MaxSec        float64                `protobuf:"fixed64,4,opt,name=max_sec,json=maxSec,proto3" json:"max_sec,omitempty"`
	ProcessMs     int64                  `protobuf:"varint,5,opt,name=process_ms,json=processMs,proto3" json:"process_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeMeta) Reset() {
	*x = SynthesizeMeta{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeMeta) ProtoMessage() {}

func (x *SynthesizeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeMeta.ProtoReflect.Descriptor instead.
func (*SynthesizeMeta) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{4}
}

func (x *SynthesizeMeta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SynthesizeMeta) GetVoiceProfile() *VoiceProfile {
	if x != nil {
		return x.VoiceProfile
	}
	return nil
}

func (x *SynthesizeMeta) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SynthesizeMeta) GetMaxSec() float64 {
	if x != nil {
		return x.MaxSec
	}
	return 0
}

func (x *SynthesizeMeta) GetProcessMs() int64 {
	if x != nil {
		return x.ProcessMs
	}
	return 0
}

type SynthesizeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SynthesizeEvent_Chunk
	//	*SynthesizeEvent_SegmentDone
	//	*SynthesizeEvent_FinalMeta
	//	*SynthesizeEvent_Error
	Event         isSynthesizeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeEvent) Reset() {
	*x = SynthesizeEvent{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeEvent) ProtoMessage() {}

func (x *SynthesizeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeEvent.ProtoReflect.Descriptor instead.
func (*SynthesizeEvent) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{5}
}

func (x *SynthesizeEvent) GetEvent() isSynthesizeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SynthesizeEvent) GetChunk() *AudioChunk {
	if x != nil {
		if x, ok := x.Event.(*SynthesizeEvent_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *SynthesizeEvent) GetSegmentDone() *SegmentDone {
	if x != nil {
		if x, ok := x.Event.(*SynthesizeEvent_SegmentDone); ok {
			return x.SegmentDone
		}
	}
	return nil
}

func (x *SynthesizeEvent) GetFinalMeta() *SynthesizeMeta {
	if x != nil {
		if x, ok := x.Event.(*SynthesizeEvent_FinalMeta); ok {
			return x.FinalMeta
		}
	}
	return nil
}

func (x *SynthesizeEvent) GetError() *SynthesizeError {
	if x != nil {
		if x, ok := x.Event.(*SynthesizeEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSynthesizeEvent_Event interface {
	isSynthesizeEvent_Event()
}

type SynthesizeEvent_Chunk struct {
	Chunk *AudioChunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type SynthesizeEvent_SegmentDone struct {
	SegmentDone *SegmentDone `protobuf:"bytes,2,opt,name=segment_done,json=segmentDone,proto3,oneof"`
}

type SynthesizeEvent_FinalMeta struct {
	FinalMeta *SynthesizeMeta `protobuf:"bytes,3,opt,name=final_meta,json=finalMeta,proto3,oneof"`
}

type SynthesizeEvent_Error struct {
	Error *SynthesizeError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SynthesizeEvent_Chunk) isSynthesizeEvent_Event() {}

func (*SynthesizeEvent_SegmentDone) isSynthesizeEvent_Event() {}

func (*SynthesizeEvent_FinalMeta) isSynthesizeEvent_Event() {}

func (*SynthesizeEvent_Error) isSynthesizeEvent_Event() {}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentIndex  int32                  `protobuf:"varint,1,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{6}
}

func (x *AudioChunk) GetSegmentIndex() int32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type SegmentDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	EstimatedSec  float64                `protobuf:"fixed64,3,opt,name=estimated_sec,json=estimatedSec,proto3" json:"estimated_sec,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentDone) Reset() {
	*x = SegmentDone{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentDone) ProtoMessage() {}

func (x *SegmentDone) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentDone.ProtoReflect.Descriptor instead.
func (*SegmentDone) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{7}
}

func (x *SegmentDone) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SegmentDone) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SegmentDone) GetEstimatedSec() float64 {
	if x != nil {
		return x.EstimatedSec
	}
	return 0
}

func (x *SegmentDone) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SegmentDone) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SynthesizeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeError) Reset() {
	*x = SynthesizeError{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeError) ProtoMessage() {}

func (x *SynthesizeError) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeError.ProtoReflect.Descriptor instead.
func (*SynthesizeError) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{8}
}

func (x *SynthesizeError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SynthesizeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	MaxSec        float64                `protobuf:"fixed64,2,opt,name=max_sec,json=maxSec,proto3" json:"max_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{9}
}

func (x *PreviewRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PreviewRequest) GetMaxSec() float64 {
	if x != nil {
		return x.MaxSec
	}
	return 0
}

type PreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Segments      []*PreviewSegment      `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewResponse) Reset() {
	*x = PreviewResponse{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResponse) ProtoMessage() {}

func (x *PreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResponse.ProtoReflect.Descriptor instead.
func (*PreviewResponse) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{10}
}

func (x *PreviewResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PreviewResponse) GetSegments() []*PreviewSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type PreviewSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	EstimatedSec  float64                `protobuf:"fixed64,3,opt,name=estimated_sec,json=estimatedSec,proto3" json:"estimated_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewSegment) Reset() {
	*x = PreviewSegment{}
	mi := &file_paraspeech_v1_tts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewSegment) ProtoMessage() {}

func (x *PreviewSegment) ProtoReflect() protoreflect.Message {
	mi := &file_paraspeech_v1_tts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewSegment.ProtoReflect.Descriptor instead.
func (*PreviewSegment) Descriptor() ([]byte, []int) {
	return file_paraspeech_v1_tts_proto_rawDescGZIP(), []int{11}
}

func (x *PreviewSegment) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PreviewSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PreviewSegment) GetEstimatedSec() float64 {
	if x != nil {
		return x.EstimatedSec
	}
	return 0
}

var File_paraspeech_v1_tts_proto protoreflect.FileDescriptor

const file_paraspeech_v1_tts_proto_rawDesc = "" +
	"\n" +
	"\x17paraspeech/v1/tts.proto\x12\rparaspeech.v1\"\xe3\x01\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12@\n" +
	"\rvoice_profile\x18\x03 \x01(\v2\x1b.paraspeech.v1.VoiceProfileR\fvoiceProfile\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x17\n" +
	"\amax_sec\x18\x06 \x01(\x01R\x06maxSec\x12\x17\n" +
	"\aout_dir\x18\a \x01(\tR\x06outDir\"\xfc\x01\n" +
	"\fVoiceProfile\x12\x14\n" +
	"\x05voice\x18\x01 \x01(\tR\x05voice\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x01R\x05speed\x12\x18\n" +
	"\aemotion\x18\x03 \x01(\tR\aemotion\x12\x14\n" +
	"\x05pitch\x18\x04 \x01(\tR\x05pitch\x12\x14\n" +
	"\x05style\x18\x05 \x01(\tR\x05style\x12?\n" +
	"\x06custom\x18\x06 \x03(\v2'.paraspeech.v1.VoiceProfile.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x12SynthesizeResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12<\n" +
	"\bsegments\x18\x02 \x03(\v2 .paraspeech.v1.SynthesizeSegmentR\bsegments\x121\n" +
	"\x04meta\x18\x03 \x01(\v2\x1d.paraspeech.v1.SynthesizeMetaR\x04meta\"\xce\x01\n" +
	"\x11SynthesizeSegment\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\restimated_sec\x18\x03 \x01(\x01R\festimatedSec\x12\x14\n" +
	"\x05audio\x18\x04 \x01(\fR\x05audio\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\"\xbb\x01\n" +
	"\x0eSynthesizeMeta\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12@\n" +
	"\rvoice_profile\x18\x02 \x01(\v2\x1b.paraspeech.v1.VoiceProfileR\fvoiceProfile\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x17\n" +
	"\amax_sec\x18\x04 \x01(\x01R\x06maxSec\x12\x1d\n" +
	"\n" +
	"process_ms\x18\x05 \x01(\x03R\tprocessMs\"\x86\x02\n" +
	"\x0fSynthesizeEvent\x121\n" +
	"\x05chunk\x18\x01 \x01(\v2\x19.paraspeech.v1.AudioChunkH\x00R\x05chunk\x12?\n" +
	"\fsegment_done\x18\x02 \x01(\v2\x1a.paraspeech.v1.SegmentDoneH\x00R\vsegmentDone\x12>\n" +
	"\n" +
	"final_meta\x18\x03 \x01(\v2\x1d.paraspeech.v1.SynthesizeMetaH\x00R\tfinalMeta\x126\n" +
	"\x05error\x18\x04 \x01(\v2\x1e.paraspeech.v1.SynthesizeErrorH\x00R\x05errorB\a\n" +
	"\x05event\"h\n" +
	"\n" +
	"AudioChunk\x12#\n" +
	"\rsegment_index\x18\x01 \x01(\x05R\fsegmentIndex\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\x8f\x01\n" +
	"\vSegmentDone\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\restimated_sec\x18\x03 \x01(\x01R\festimatedSec\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"?\n" +
	"\x0fSynthesizeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x0ePreviewRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\amax_sec\x18\x02 \x01(\x01R\x06maxSec\"b\n" +
	"\x0fPreviewResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x129\n" +
	"\bsegments\x18\x02 \x03(\v2\x1d.paraspeech.v1.PreviewSegmentR\bsegments\"_\n" +
	"\x0ePreviewSegment\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\restimated_sec\x18\x03 \x01(\x01R\festimatedSec2\x81\x02\n" +
	"\n" +
	"TTSService\x12Q\n" +
	"\n" +
	"Synthesize\x12 .paraspeech.v1.SynthesizeRequest\x1a!.paraspeech.v1.SynthesizeResponse\x12V\n" +
	"\x10SynthesizeStream\x12 .paraspeech.v1.SynthesizeRequest\x1a\x1e.paraspeech.v1.SynthesizeEvent0\x01\x12H\n" +
	"\aPreview\x12\x1d.paraspeech.v1.PreviewRequest\x1a\x1e.paraspeech.v1.PreviewResponseB1Z/paraspeech/api/proto/paraspeech/v1;paraspeechv1b\x06proto3"

var (
	file_paraspeech_v1_tts_proto_rawDescOnce sync.Once
	file_paraspeech_v1_tts_proto_rawDescData []byte
)

func file_paraspeech_v1_tts_proto_rawDescGZIP() []byte {
	file_paraspeech_v1_tts_proto_rawDescOnce.Do(func() {
		file_paraspeech_v1_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paraspeech_v1_tts_proto_rawDesc), len(file_paraspeech_v1_tts_proto_rawDesc)))
	})
	return file_paraspeech_v1_tts_proto_rawDescData
}

var file_paraspeech_v1_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_paraspeech_v1_tts_proto_goTypes = []any{
	(*SynthesizeRequest)(nil),  // 0: paraspeech.v1.SynthesizeRequest
	(*VoiceProfile)(nil),       // 1: paraspeech.v1.VoiceProfile
	(*SynthesizeResponse)(nil), // 2: paraspeech.v1.SynthesizeResponse
	(*SynthesizeSegment)(nil),  // 3: paraspeech.v1.SynthesizeSegment
	(*SynthesizeMeta)(nil),     // 4: paraspeech.v1.SynthesizeMeta
	(*SynthesizeEvent)(nil),    // 5: paraspeech.v1.SynthesizeEvent
	(*AudioChunk)(nil),         // 6: paraspeech.v1.AudioChunk
	(*SegmentDone)(nil),        // 7: paraspeech.v1.SegmentDone
	(*SynthesizeError)(nil),    // 8: paraspeech.v1.SynthesizeError
	(*PreviewRequest)(nil),     // 9: paraspeech.v1.PreviewRequest
	(*PreviewResponse)(nil),    // 10: paraspeech.v1.PreviewResponse
	(*PreviewSegment)(nil),     // 11: paraspeech.v1.PreviewSegment
	nil,                        // 12: paraspeech.v1.VoiceProfile.CustomEntry
}
var file_paraspeech_v1_tts_proto_depIdxs = []int32{
	1,  // 0: paraspeech.v1.SynthesizeRequest.voice_profile:type_name -> paraspeech.v1.VoiceProfile
	12, // 1: paraspeech.v1.VoiceProfile.custom:type_name -> paraspeech.v1.VoiceProfile.CustomEntry
	3,  // 2: paraspeech.v1.SynthesizeResponse.segments:type_name -> paraspeech.v1.SynthesizeSegment
	4,  // 3: paraspeech.v1.SynthesizeResponse.meta:type_name -> paraspeech.v1.SynthesizeMeta
	1,  // 4: paraspeech.v1.SynthesizeMeta.voice_profile:type_name -> paraspeech.v1.VoiceProfile
	6,  // 5: paraspeech.v1.SynthesizeEvent.chunk:type_name -> paraspeech.v1.AudioChunk
	7,  // 6: paraspeech.v1.SynthesizeEvent.segment_done:type_name -> paraspeech.v1.SegmentDone
	4,  // 7: paraspeech.v1.SynthesizeEvent.final_meta:type_name -> paraspeech.v1.SynthesizeMeta
	8,  // 8: paraspeech.v1.SynthesizeEvent.error:type_name -> paraspeech.v1.SynthesizeError
	11, // 9: paraspeech.v1.PreviewResponse.segments:type_name -> paraspeech.v1.PreviewSegment
	0,  // 10: paraspeech.v1.TTSService.Synthesize:input_type -> paraspeech.v1.SynthesizeRequest
	0,  // 11: paraspeech.v1.TTSService.SynthesizeStream:input_type -> paraspeech.v1.SynthesizeRequest
	9,  // 12: paraspeech.v1.TTSService.Preview:input_type -> paraspeech.v1.PreviewRequest
	2,  // 13: paraspeech.v1.TTSService.Synthesize:output_type -> paraspeech.v1.SynthesizeResponse
	5,  // 14: paraspeech.v1.TTSService.SynthesizeStream:output_type -> paraspeech.v1.SynthesizeEvent
	10, // 15: paraspeech.v1.TTSService.Preview:output_type -> paraspeech.v1.PreviewResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_paraspeech_v1_tts_proto_init() }
func file_paraspeech_v1_tts_proto_init() {
	if File_paraspeech_v1_tts_proto != nil {
		return
	}
	file_paraspeech_v1_tts_proto_msgTypes[5].OneofWrappers = []any{
		(*SynthesizeEvent_Chunk)(nil),
		(*SynthesizeEvent_SegmentDone)(nil),
		(*SynthesizeEvent_FinalMeta)(nil),
		(*SynthesizeEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paraspeech_v1_tts_proto_rawDesc), len(file_paraspeech_v1_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paraspeech_v1_tts_proto_goTypes,
		DependencyIndexes: file_paraspeech_v1_tts_proto_depIdxs,
		MessageInfos:      file_paraspeech_v1_tts_proto_msgTypes,
	}.Build()
	File_paraspeech_v1_tts_proto = out.File
	file_paraspeech_v1_tts_proto_goTypes = nil
	file_paraspeech_v1_tts_proto_depIdxs = nil
}
